### ISSUE TITLE
Investigate options for hosting app

### ISSUE THREAD

**Issue by kyrod** [Goldify/Goldify#14]
**Is your feature request related to a problem? Please describe.**

We do not currently have anywhere to host this app. We should look into various solutions to easily host our app, so that it is accessible by users
**Describe the solution you'd like**

We should have a list of possible hosting solutions with pros/cons for each

**Comment by MattGrantUMich** [comment]
Call on 11/16/20 - We're leaning towards AWS for this once we get a Proof of Concept built out. This would likely be the easiest setting up, as well as developing on, not only because we both have experience on AWS, but because it is pretty dang fast. Not to mention the AWS console is really convenient.

**Comment by MattGrantUMich** [comment]
We have investigated!
